[package]
name = "fastcaster"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
softbuffer = "0.2.1"
vek = { version = "0.15.10", features = ["bytemuck", "serde"] }
winit = "0.28.6"
